
export const iniplayerList1 = [
    '1 Rashel Mahmud (GK)',
    '2 MD R Hasan',
    '3 Topu Berman',
    '4 Razul Karim Sr.',
    '5 Yeasin Khan',
    '6 Jamal Bhuyan Sr.',
    '9 N N Ziban Sr.',
    '16 Masuk Miah Zoni',
    '11 Sohel Rana',
    '14 A R Fahad',
    '8 S A Shahed',
    '18 Anisur Rahman (GK)',
    '20 MD Razib (GK)',
    '7 Rubel Miya',
    '10 H V Biswas',
    '12 Shakil Ahmad',
    '13 Fazlay Rabbi',
    '15 A S Yosuf Sifat',
    '17 Jewal Rana',
    '19 Aminur R Sojib',
    'Coach- G S Moreno'
]
export const iniplayerList2 = [
    '36 Abhishek Chatterjee',
    '37 Ashutosh Verma',
    '38 Bharat Batham',
    '39 Jagat Sharma',
    '40 Narendra Mahawar',
    '41 Rohit Jadhav',
    '42 Sunder Verma',
    '43 Akash Dongre',
    '44 Anish Joshi',
    '45 Narsimha Chavhan',
    '46 Prithviraj Phadnis',
    '47 Sagar Sawant',
    '49 Vinayak Auti',
    '50 B Tulshidas Sharma',
    '51 Ch Meiraba Meitei',
    '52 K Roopakanta Sharma',
    '53 Rajeev Gopinathan',
    '54 M Chandrashekhar',
    '55 Peter Rose',
    '56 V B Hadap',
    'Coach-Muttu Panigrahi',
]
