
export const iniplayerList1 = [
    '1 Rashel Mahmud (GK)',
    '2 MD R Hasan',
    '3 Topu Berman',
    '4 Razul Karim Sr.',
    '5 Yeasin Khan',
    '6 Jamal Bhuyan Sr.',
    '9 N N Ziban Sr.',
    '16 Masuk Miah Zoni',
    '11 Sohel Rana',
    '14 A R Fahad',
    '8 S A Shahed',
    '18 Anisur Rahman (GK)',
    '20 MD Razib (GK)',
    '7 Rubel Miya',
    '10 H V Biswas',
    '12 Shakil Ahmad',
    '13 Fazlay Rabbi',
    '15 A S Yosuf Sifat',
    '17 Jewal Rana',
    '19 Aminur R Sojib',
    'Coach- G S Moreno'
]
export const iniplayerList2 = [
    '36 Abhishek Chatterjee',
    '37 Ashutosh Verma',
    '38 Bharat Batham',
    '39 Jagat Sharma',
    '40 Narendra Mahawar',
    '41 Rohit Jadhav',
    '42 Sunder Verma',
    '43 Akash Dongre',
    '44 Anish Joshi',
    '45 Narsimha Chavhan',
    '46 Prithviraj Phadnis',
    '47 Sagar Sawant',
    '49 Vinayak Auti',
    '50 B Tulshidas Sharma',
    '51 Ch Meiraba Meitei',
    '52 K Roopakanta Sharma',
    '53 Rajeev Gopinathan',
    '54 M Chandrashekhar',
    '55 Peter Rose',
    '56 V B Hadap',
    'Coach-Muttu Panigrahi',
]


export const iniTwoLiner = [
   { name:'1 Rashel Mahmud (GK)',designation:'Enineering Assistant, DDK Mumbai 1'},
   { name:'2 MD R Hasan', designation:'Enineering Assistant, DDK Mumbai 2'},
   { name:'3 Topu Berman',designation:'Enineering Assistant, DDK Mumbai 3'},
   { name: '4 Razul Karim Sr.',designation:'Enineering Assistant, DDK Mumbai 4'},
   { name: '5 Yeasin Khan',designation:'Enineering Assistant, DDK Mumbai 5'},
   { name: '6 Jamal Bhuyan Sr.',designation:'Enineering Assistant, DDK Mumbai 6'},
   { name: '9 N N Ziban Sr.',designation:'Enineering Assistant, DDK Mumbai 7'},
   { name: '16 Masuk Miah Zoni',designation:'Enineering Assistant, DDK Mumbai 8'},
   { name:'11 Sohel Rana',designation:'Enineering Assistant, DDK Mumbai 9'},
   { name: '14 A R Fahad',designation:'Enineering Assistant, DDK Mumbai 10'},
   { name:'8 S A Shahed',designation:'Enineering Assistant, DDK Mumbai 11'},
   { name: '18 Anisur Rahman (GK)',designation:'Enineering Assistant, DDK Mumbai 12'},
   { name: '20 MD Razib (GK)',designation:'Enineering Assistant, DDK Mumbai 13'},
   { name:'7 Rubel Miya',designation:'Enineering Assistant, DDK Mumbai 14'},
   { name: '10 H V Biswas',designation:'Enineering Assistant, DDK Mumbai 15'},
   { name:'12 Shakil Ahmad',designation:'Enineering Assistant, DDK Mumbai 16'},
   { name:'13 Fazlay Rabbi',designation:'Enineering Assistant, DDK Mumbai 17'}
  
]